added support for math typesetting by changing markdown parser to markdown-it and using a KaTeX plugin
DylanAllen/noiiice pull request #28
Opened 2020-10-08 06:47 UTC by airpaio

I Changed markdown renderer from marked to markdown-it, and also included a markdown-it-katex plugin to support math typesetting. The app needs a full redeploy for the changes to take effect.

Sample output from a post is seen below.

![image](https://user-images.githubusercontent.com/5142567/95424073-bc175980-0907-11eb-9c83-b14c3bea9e0b.png)

2020-10-08 12:35 UTC, DylanAllen requested changes

2020-10-08 12:35 UTC, DylanAllen commented on apps/app/pages/edit/_post.vue
> +        }
Can you include these css files in the repo and import from there? I want to avoid adding external resources/requests if possible.

2020-10-08 22:19 UTC, airpaio commented
I was having the same thoughts about the external stylesheets.

I completely removed the github-markdown stylesheet dependency. I don't think it's really necessary unless you wanted to use github styling in the future.

For the KaTeX stylesheet, I had to install and include the katex 0.12.0 dependency in the package.lock so that the stylesheet would have access to the fonts needed.

Initially i was thinking to just reference the stylesheets in the _post.vue files since that's really the only place markdown/katex would be used. I ended up just including the katex css globally alongside the highlightjs stylesheet in nuxt.config.js.

2020-10-09 13:14 UTC, DylanAllen commented
Looks great, thanks!

2020-10-09 13:14 UTC, merged